stages:
  - Dependencies
variables:
  CI_DEBUG_TRACE: "true"
Push zAppBuild:
  stage: Dependencies
  script:
  - |
    echo "Push zAppBuild project to USS"
  tags:
    - SD1H
  only :
    variables:
      - $CI_PIPELINE_SOURCE == 'pipeline'
