stages:
  - Dependencies
  - Refresh
Push zAppBuild:
  stage: Dependencies
  script:
  - |
    echo "Push zAppBuild project to USS"
  tags:
    - SD1H
  only :
    variables:
      - $CI_PIPELINE_SOURCE == 'pipeline'



#This job will update the /u/lpp/GIT/runner/dbb-zappbuild used by iddz developers
# It will run only if there is a commit to main branch via push or merge 
Push zAppBuild_for_IDZ:
  stage: Refresh
  script:
  - |
    env
    mdir=/u/lpp/GIT/runner
    cd $mdir
    echo "Pushing zAppBuild project to /u/lpp/GIT/runner/zappbuild"
    cd $mdir/dbb-zappbuild && git pull https://gitlab-ci-token:${GROUP_GITLAB_TOKEN}@mygit.aafes.com/${CI_PROJECT_NAMESPACE}/dbb-zappbuild.git || git clone -c http.sslVerify=false https://gitlab-ci-token:${GROUP_GITLAB_TOKEN}@mygit.aafes.com/${CI_PROJECT_NAMESPACE}/dbb-zappbuild.git
    cd $mdir/dbb-zappbuild
    git switch main
  tags:
    - SD1H
  rules:
    - if: ($CI_PIPELINE_SOURCE != 'pipeline' && $CI_COMMIT_BRANCH == 'main')

