stages:
  - Dependencies
Push zAppBuild:
  stage: Dependencies
  script:
  - |
    echo "Push zAppBuild project to USS"
    echo "sleeping for 60"
    sleep 60
  tags:
    - SD1H
  only :
    variables:
      - $CI_PIPELINE_SOURCE == 'pipeline'
